from pathlib import Path
import json
import unittest


ROOT = Path(__file__).resolve().parents[1]
PAGE_DIR = ROOT / "pages" / "linghui-studio"


class WebUiThemeAssetsTest(unittest.TestCase):
    def test_shell_frame_themes_and_brand_assets_are_packaged(self):
        script = (PAGE_DIR / "app.js").read_text(encoding="utf-8")
        html = (PAGE_DIR / "index.html").read_text(encoding="utf-8")
        stylesheet = (PAGE_DIR / "style.css").read_text(encoding="utf-8")
        api = (ROOT / "dashboard_api.py").read_text(encoding="utf-8")
        schema = json.loads((ROOT / "_conf_schema.json").read_text(encoding="utf-8"))
        sprite = PAGE_DIR / "assets" / "alice-sprite.png"
        brand_logo = PAGE_DIR / "assets" / "linghui-logo.svg"

        self.assertIn('"alice"', script)
        self.assertIn('"nebula"', script)
        self.assertIn('renderSessionOverrides', script)
        self.assertIn('bridge.apiGet("session_overrides")', script)
        self.assertIn('data-session-clear', script)
        self.assertIn('data-channel="protocol"', script)
        self.assertIn('protocol_labels', script)
        self.assertIn('id="session-override-list"', html)
        self.assertIn('id="batch-failure-policy"', html)
        self.assertIn('id="enable-binary-image-response"', html)
        self.assertIn('.session-override-card', stylesheet)
        self.assertIn('changeTheme', script)
        self.assertIn('apiPost("dashboard_theme"', script)
        self.assertIn('id="theme-select"', html)
        self.assertIn('value="alice"', html)
        self.assertIn('data-theme-option="alice"', html)
        self.assertIn('value="terminal"', html)
        self.assertIn('data-theme-option="terminal"', html)
        self.assertIn('value="nebula"', html)
        self.assertIn('data-theme-option="nebula"', html)
        self.assertIn('theme-menu-toggle', html)
        self.assertIn('class="nav-group"', html)
        self.assertIn('class="save-action"', html)
        self.assertNotIn('INTERFACE PROFILE', html)
        self.assertIn('src="./assets/linghui-logo.svg"', html)
        self.assertIn('href="./assets/linghui-logo.svg"', html)
        self.assertIn('url("./assets/alice-sprite.png")', stylesheet)
        self.assertIn('html[data-theme="alice"]', stylesheet)
        self.assertIn('html[data-theme="terminal"]', stylesheet)
        self.assertIn('html[data-theme="nebula"]', stylesheet)
        self.assertIn('terminal-cursor', stylesheet)
        self.assertIn('body::after', stylesheet)
        self.assertIn('backdrop-filter: blur', stylesheet)
        self.assertIn('.statusbar', stylesheet)
        self.assertIn('.tabstrip-track', stylesheet)
        self.assertIn('.save-action', stylesheet)
        self.assertIn('body::before', stylesheet)
        self.assertIn('--grid-line-minor', stylesheet)
        self.assertIn('--grid-line-major', stylesheet)
        self.assertIn('linear-gradient', stylesheet)
        self.assertGreaterEqual(stylesheet.count('--grid-line-minor'), 3)
        self.assertGreaterEqual(stylesheet.count('--grid-line-major'), 3)
        self.assertIn('generation_preview', script)
        self.assertIn('bridge.apiGet("generation_preview"', script)
        self.assertIn('generation_prompt', script)
        self.assertIn('generation_sources', script)
        self.assertIn('generation_source_preview', script)
        self.assertIn('generation_source_download', script)
        self.assertIn('formatGenerationChannel', script)
        self.assertIn('generation-route-badge', script)
        self.assertIn('.generation-route-badge', stylesheet)
        self.assertIn('data-tab="image-to-image"', html)
        self.assertIn('id="history-group-filter"', html)
        self.assertIn('id="history-user-filter"', html)
        self.assertIn('historyGroupId', script)
        self.assertIn('historyUserId', script)
        self.assertIn('overview-toolbar', html)
        self.assertIn('overview-dispatch-bar', html)
        self.assertIn('overview-channels', html)
        self.assertIn('overview-recent', html)
        self.assertIn('history-toolbar', html)
        self.assertNotIn('history-metric-grid', html)
        self.assertIn('generation-sources', script)
        self.assertIn('status !== "legacy_unavailable"', script)
        self.assertIn('const sourceSummary', script)
        self.assertIn('.history-toolbar', stylesheet)
        self.assertIn('.overview-toolbar', stylesheet)
        self.assertIn('.overview-dispatch-bar', stylesheet)
        self.assertIn('.overview-route-chip', stylesheet)
        self.assertIn('.overview-content-grid { display: grid; grid-template-columns: minmax(0, 1fr)', stylesheet)
        self.assertIn('.overview-usage-panel .usage-table', stylesheet)
        self.assertIn('.overview-recent-panel', stylesheet)
        self.assertIn('.generation-source-grid', stylesheet)
        self.assertIn('GENERATION_PREVIEW_CONCURRENCY = 2', script)
        self.assertIn('IntersectionObserver', script)
        self.assertIn('grid-template-rows: auto auto minmax(0, 1fr) auto', stylesheet)
        self.assertIn('100dvh', stylesheet)
        self.assertIn('html[data-density="compact"]', stylesheet)
        self.assertNotIn('.sidebar-console', stylesheet)
        self.assertNotIn('class="sidebar"', html)
        self.assertIn('id="density-toggle"', html)
        self.assertIn('id="status-summary"', html)
        self.assertIn('id="status-dispatch"', html)
        self.assertIn('id="status-breadcrumb"', html)
        self.assertIn('class="tabstrip-track"', html)
        self.assertIn('updateStatusBar', script)
        self.assertIn('setTabBadge', script)
        self.assertIn('apiPost("dashboard_density"', script)
        self.assertNotIn('content: "//"', stylesheet)
        self.assertIn('save_dashboard_theme', api)
        self.assertIn('save_dashboard_density', api)
        self.assertEqual(schema["dashboard_density"]["default"], "comfortable")
        self.assertIn("compact", schema["dashboard_density"]["options"])
        self.assertEqual(schema["dashboard_theme"]["default"], "dark")
        self.assertIn("terminal", schema["dashboard_theme"]["options"])
        self.assertIn("nebula", schema["dashboard_theme"]["options"])
        self.assertTrue(sprite.is_file())
        self.assertEqual(sprite.read_bytes()[:8], b"\x89PNG\r\n\x1a\n")
        self.assertTrue(brand_logo.is_file())
        self.assertIn("<svg", brand_logo.read_text(encoding="utf-8"))
